Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/finn/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 104, in on_message
    await channel.send(" URL: " + message.embeds[0].url)
IndexError: list index out of range
