Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/finn/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 103, in on_message
    message = client.fetch_message(782346623471845446)
AttributeError: 'Client' object has no attribute 'fetch_message'
teajnfs
Connected to Discord!
