Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/finn/.local/lib/python3.7/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "bot.py", line 107, in on_message
    filepath.unlink()
  File "/usr/lib/python3.7/pathlib.py", line 1287, in unlink
    self._accessor.unlink(self)
IsADirectoryError: [Errno 21] Is a directory: '/home/finn/serpens_addon_market'
Connected to Discord!
[main 93bd002] Updated or added an addon
 6 files changed, 69 insertions(+), 26 deletions(-)
 create mode 100644 addons/gitbuildbot657253258712317952.py
 rewrite open_entries.json (99%)
 create mode 100644 output.log
 create mode 100644 run.sh
To github.com:joshuaKnauber/serpens_addon_market.git
   0dc69bb..93bd002  main -> main
Connected to Discord!
rm: fehlender Operand
„rm --help“ liefert weitere Informationen.
[main e49163d] Updated or added an addon
 5 files changed, 191 insertions(+), 119 deletions(-)
 create mode 100644 addons/bot657253258712317952.py
 delete mode 100644 addons/gui657253258712317952.py
To github.com:joshuaKnauber/serpens_addon_market.git
   93bd002..e49163d  main -> main
Connected to Discord!
rm: fehlender Operand
„rm --help“ liefert weitere Informationen.
[main 3973a27] Updated or added an addon
 3 files changed, 12 insertions(+), 3 deletions(-)
To github.com:joshuaKnauber/serpens_addon_market.git
   e49163d..3973a27  main -> main
rm: fehlender Operand
„rm --help“ liefert weitere Informationen.
